import { ArrowRight, BarChart3, CalendarCheck2, FileText, LockKeyhole, MessageSquare, ShieldCheck, Users, Workflow } from "lucide-react";
import { Reveal } from "@/components/ui/Reveal";
import type { Copy } from "@/lib/content";

const icons = [Users, CalendarCheck2, FileText, LockKeyhole, ShieldCheck, MessageSquare, Workflow];

export function ProductSection({ text }: { text: Copy }) {
  return <section id="product" className="section-rule mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-16 lg:grid-cols-[.7fr_1.3fr]"><Reveal><p className="eyebrow">{text.product.eyebrow}</p><h2 className="section-title mt-12 max-w-xl">{text.product.title}</h2><p className="mt-8 max-w-md text-lg leading-8 text-white/55">{text.product.subtitle}</p></Reveal><Reveal className="min-w-0" delay={.08}><div className="product-canvas overflow-hidden rounded-[2rem] border border-white/10 bg-[#0d1324] p-3 shadow-2xl shadow-black/20 sm:p-4"><div className="flex flex-wrap items-center gap-3 border-b border-white/10 px-3 pb-4"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-white/20" /><span className="h-2 w-2 rounded-full bg-white/20" /><span className="h-2 w-2 rounded-full bg-white/20" /></div><span className="text-[10px] text-white/40">{text.product.workspaceLabel}</span><span className="ml-auto rounded-full border border-cyan/20 bg-cyan/10 px-2 py-1 text-[9px] text-cyan">{text.product.secureSystem}</span></div><div className="grid gap-3 p-1 pt-4 sm:grid-cols-[.54fr_1.46fr]"><div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><p className="mb-3 px-2 text-[9px] uppercase tracking-[.16em] text-white/30">{text.product.navigationLabel}</p>{text.product.modules.map(([name], index) => { const Icon = icons[index]; return <div key={name} className={`flex items-center gap-2 rounded-lg px-2.5 py-2.5 text-[11px] ${index === 0 ? "bg-cyan/10 text-cyan-soft" : "text-white/45"}`}><Icon className="h-3.5 w-3.5" />{name}</div>; })}</div><div className="rounded-2xl border border-white/[.07] bg-white/[.025] p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] uppercase tracking-[.16em] text-cyan/70">{text.product.overviewLabel}</p><p className="mt-3 text-xl tracking-[-.04em] text-white/85">{text.product.overviewTitle}</p></div><BarChart3 className="h-5 w-5 shrink-0 text-cyan/70" /></div><ul className="mt-8 grid gap-3 sm:grid-cols-3">{text.product.modules.slice(0, 3).map(([name, description]) => <li key={name} className="rounded-xl border border-white/[.07] bg-white/[.025] p-3"><span className="mb-4 block h-2 w-2 rounded-full bg-cyan" /><p className="text-xs text-white/75">{name}</p><p className="mt-1 text-[10px] leading-4 text-white/30">{description}</p></li>)}</ul><div className="mt-3 flex items-center justify-between gap-3 rounded-xl border border-cyan/15 bg-cyan/[.045] px-4 py-3"><span className="text-[10px] text-white/50">{text.product.operationalContext}</span><ArrowRight className="h-4 w-4 shrink-0 text-cyan" /></div></div></div></div></Reveal></div></section>;
}
