import { MapPin } from "lucide-react";
import { Reveal } from "@/components/ui/Reveal";
import type { Copy } from "@/lib/content";

export function WhyWeStarted({ text }: { text: Copy }) {
  return <section id="story" className="section-rule mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-16 lg:grid-cols-[.6fr_1.4fr]"><Reveal><p className="eyebrow">{text.why.eyebrow}</p></Reveal><Reveal className="max-w-4xl"><p className="max-w-3xl text-3xl font-light leading-[1.06] tracking-[-.055em] text-white/90 sm:text-5xl">{text.why.title}</p><p className="mt-6 text-xl tracking-[-.03em] text-cyan">{text.why.lead}</p><ul className="mt-14 grid max-w-2xl grid-cols-2 gap-x-8 gap-y-4 border-t border-white/10 pt-6 sm:grid-cols-3">{text.why.lines.map((line) => <li key={line} className="flex gap-2 text-sm text-white/60"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-cyan" />{line}</li>)}</ul><p className="mt-16 max-w-2xl border-l-2 border-cyan/60 pl-5 text-lg leading-8 text-white/65">{text.why.closing}</p></Reveal></div></section>;
}

export function RealSchoolSection({ text }: { text: Copy }) {
  return <section className="section-rule mx-auto max-w-7xl px-6 py-28 lg:px-10 lg:py-40"><div className="grid gap-16 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="eyebrow">{text.school.eyebrow}</p><h2 className="section-title mt-12 max-w-3xl">{text.school.title}</h2><p className="mt-8 max-w-2xl text-lg leading-8 text-white/60">{text.school.text}</p><p className="mt-9 flex items-center gap-2 text-xs uppercase tracking-[.14em] text-cyan"><MapPin className="h-4 w-4" />{text.school.location}</p></Reveal><Reveal className="flex min-w-0 flex-col justify-end" delay={.08}><div className="school-marker relative overflow-hidden rounded-[2rem] border border-cyan/20 bg-cyan/[.045] p-6 sm:p-8"><div className="absolute -right-16 -top-16 h-48 w-48 rounded-full bg-cyan/10 blur-3xl" /><p className="relative text-[10px] uppercase tracking-[.18em] text-cyan/70">{text.school.flowLabel}</p><ul className="relative mt-14 space-y-5">{text.school.items.map((item) => <li key={item} className="flex items-center gap-3 border-b border-white/[.08] pb-3 last:border-0"><span className="h-2 w-2 shrink-0 rounded-full bg-cyan" /><span className="min-w-0 text-sm text-white/75">{item}</span></li>)}</ul><p className="relative mt-8 border-t border-cyan/20 pt-5 text-sm leading-6 text-white/55">{text.school.note}</p></div><ul className="mt-8 grid grid-cols-2 gap-y-3 px-1 text-[10px] uppercase tracking-[.16em] text-white/30 sm:flex sm:justify-between sm:gap-0">{text.school.stages.map((stage) => <li key={stage} className="text-cyan">{stage}</li>)}</ul></Reveal></div></section>;
}
