export type Language = "en" | "es";

export const copy = {
  en: {
    nav: { home: "Home", story: "Why we started", product: "What we build", school: "First school", ai: "Principles", vision: "Vision", team: "Team", contact: "Contact", cta: "Talk to us" },
    hero: { badge: "A real project, taking its next step", headline: "Software for schools, built from inside a school.", subtitle: "We are a student-founded company building NUVRA: a flexible system for the way each school actually works. Our first school is where the idea started — and where it is being tested for real.", primary: "See what is working", secondary: "Our story", note: "Made to be adapted, not imposed.", productLabel: "NUVRA / school workspace", productItems: ["Students", "Attendance", "Reports", "Permissions", "Roles", "Communication"], mockupTagline: "A clearer day for everyone in the school.", connected: "In validation", modulesLabel: "For the whole school", operationsLabel: "A school day, connected", secureRoles: "Different people, different needs", secureRolesDescription: "One base, adapted to each role.", assistance: "Built around real routines", assistanceDescription: "Less scattered information, more shared context.", contextFlow: "From a school project to a product for many schools" },
    why: { eyebrow: "Why we started", title: "NUVRA began as a school project. It became a company because the problem was real.", lead: "We were not looking for a problem to solve. We were living it.", lines: ["Messages in different places.", "Paper and spreadsheets.", "Information that does not reach everyone.", "Manual coordination.", "A school ready to become more digital."], closing: "We are building software from inside the environment it needs to understand — with the people who use it every day." },
    school: { eyebrow: "Our first school", title: "The E.E.S.T. N.º 1 Manuel Belgrano is our starting point, not our limit.", text: "We are students at the school where NUVRA began. There is already a working demo, courses using parts of the system and users testing it. In the coming days, the school will decide whether NUVRA can become part of everyday life next year.", items: ["Communication with families", "Student records", "Attendance", "Permissions", "Reports", "Roles", "Administrative coordination"], note: "What works here becomes a lesson for every school we build with next.", location: "Santos Lugares · Buenos Aires · Argentina", stages: ["School project", "Demo", "Testing", "Everyday use"], flowLabel: "From our school to many schools" },
    product: { eyebrow: "What we build", title: "A flexible base for the way each school works.", subtitle: "NUVRA brings the important parts of school life closer together — while leaving room for each institution's routines, people and decisions.", modules: [["Students", "Records and context"], ["Attendance", "Daily visibility"], ["Reports", "Clearer information"], ["Permissions", "Requests and review"], ["Roles", "The right access"], ["Communication", "Connected families and teams"], ["Workflows", "Less manual work"]], workspaceLabel: "NUVRA / school workspace", secureSystem: "Adaptable system", navigationLabel: "Built around your school", overviewLabel: "A shared view", overviewTitle: "The right information, for the right people.", operationalContext: "Every school can shape its own way of working." },
    ai: { eyebrow: "Our principles", title: "Technology should make school life clearer, not more complicated.", text: "We care about useful software first. If a tool does not help a student, family, teacher or school team, it does not belong in the product. Future assistance features will support people — never replace their judgment.", flow: [["Listen first", "We begin with the routines already inside a school"], ["Adapt", "Each institution can shape its own workflows"], ["Connect", "Information reaches the people who need it"], ["Keep people in control", "Schools decide how the product is used"]], note: "A young company, learning in public and building carefully.", loopLabel: "How we want to build", reviewLabel: "People keep the context and the final decision.", statusLabel: "Useful, human, adaptable" },
    vision: { eyebrow: "Our vision", title: "Our school is the first of many.", text: "We want schools to have software that respects the way they work, the people who make them run and the communities around them. NUVRA is starting locally, with a real product and a real school, with the ambition to grow one institution at a time.", closing: "We are not trying to arrive with all the answers. We are building the right ones with schools." },
    roadmap: { eyebrow: "Where we are", title: "A company in its first real chapter.", items: [["NOW", "Demo working inside our school"], ["NEXT", "Decision about everyday use"], ["THEN", "Improve what people actually use"], ["LATER", "Build with more institutions"]] },
    team: { eyebrow: "The team", title: "Students building something useful from Buenos Aires.", text: "We are a student-founded technical team combining software development, product thinking and direct experience inside a real school environment.", members: [["Francisco Ulises González Feldman", "Founder / Technical Lead"], ["Santino Conejo Palacios", "Co-founder"], ["Benjamin Tomas Ison Iannello", "Early team"], ["Martin Valentino Lissi", "Early team"], ["Agustin Morales", "Early team"]] },
    contact: { eyebrow: "Contact", title: "If your school has a problem, we want to understand it.", text: "For pilots, partnerships, startup programs or product conversations, reach out to the team building NUVRA from inside a school.", button: "Talk to the team", email: "founders@nuvraacademy.com.ar" },
    footer: "Nuvra Academy — Building software for schools, one institution at a time.",
  },
  es: {
    nav: { home: "Inicio", story: "Por qué empezamos", product: "Qué construimos", school: "Primera escuela", ai: "Principios", vision: "Visión", team: "Equipo", contact: "Contacto", cta: "Hablemos" },
    hero: { badge: "Un proyecto real dando su próximo paso", headline: "Software para escuelas, construido desde una escuela.", subtitle: "Somos una empresa fundada por estudiantes y estamos construyendo NUVRA: un sistema flexible para la forma en que realmente trabaja cada escuela. Nuestra primera escuela es donde nació la idea y donde se está probando de verdad.", primary: "Ver qué funciona hoy", secondary: "Nuestra historia", note: "Pensado para adaptarse, no para imponerse.", productLabel: "NUVRA / espacio escolar", productItems: ["Estudiantes", "Asistencia", "Reportes", "Permisos", "Roles", "Comunicación"], mockupTagline: "Un día más claro para toda la escuela.", connected: "En validación", modulesLabel: "Para toda la escuela", operationsLabel: "Una jornada conectada", secureRoles: "Distintas personas, distintas necesidades", secureRolesDescription: "Una base, adaptada a cada rol.", assistance: "Construido sobre rutinas reales", assistanceDescription: "Menos información dispersa, más contexto compartido.", contextFlow: "De un proyecto escolar a un producto para muchas escuelas" },
    why: { eyebrow: "Por qué empezamos", title: "NUVRA empezó como un proyecto escolar. Se convirtió en una empresa porque el problema era real.", lead: "No estábamos buscando un problema para resolver. Lo estábamos viviendo.", lines: ["Mensajes en distintos lugares.", "Papeles y planillas.", "Información que no llega a todos.", "Coordinación manual.", "Una escuela lista para digitalizarse."], closing: "Estamos construyendo software desde el entorno que necesita entender, junto a las personas que lo usan todos los días." },
    school: { eyebrow: "Nuestra primera escuela", title: "La E.E.S.T. N.º 1 Manuel Belgrano es nuestro punto de partida, no nuestro límite.", text: "Somos estudiantes de la escuela donde nació NUVRA. Ya existe una demo funcionando, hay cursos usando partes del sistema y usuarios que lo están probando. En los próximos días, la escuela decidirá si NUVRA puede formar parte del día a día durante el próximo año.", items: ["Comunicación con familias", "Registros de estudiantes", "Asistencia", "Permisos", "Reportes", "Roles", "Coordinación administrativa"], note: "Lo que funciona acá se convierte en aprendizaje para cada escuela con la que construyamos después.", location: "Santos Lugares · Buenos Aires · Argentina", stages: ["Proyecto escolar", "Demo", "Pruebas", "Uso diario"], flowLabel: "De nuestra escuela a muchas escuelas" },
    product: { eyebrow: "Qué construimos", title: "Una base flexible para la forma en que trabaja cada escuela.", subtitle: "NUVRA acerca las partes importantes de la vida escolar, dejando espacio para las rutinas, las personas y las decisiones propias de cada institución.", modules: [["Estudiantes", "Registros y contexto"], ["Asistencia", "Visibilidad diaria"], ["Reportes", "Información más clara"], ["Permisos", "Solicitudes y revisión"], ["Roles", "El acceso correcto"], ["Comunicación", "Familias y equipos conectados"], ["Flujos", "Menos trabajo manual"]], workspaceLabel: "NUVRA / espacio escolar", secureSystem: "Sistema adaptable", navigationLabel: "Construido alrededor de tu escuela", overviewLabel: "Una visión compartida", overviewTitle: "La información correcta para las personas indicadas.", operationalContext: "Cada escuela puede definir su propia forma de trabajar." },
    ai: { eyebrow: "Nuestros principios", title: "La tecnología debería hacer más clara la vida escolar, no complicarla.", text: "Nos importa que el software sea útil primero. Si una herramienta no ayuda a un estudiante, una familia, un docente o un equipo escolar, no tiene lugar en el producto. Las futuras funciones de asistencia van a acompañar a las personas, nunca reemplazar su criterio.", flow: [["Escuchar primero", "Empezamos con las rutinas que ya existen en una escuela"], ["Adaptar", "Cada institución puede definir sus propios flujos"], ["Conectar", "La información llega a quienes la necesitan"], ["Dejar decidir", "Las escuelas mantienen el control del producto"]], note: "Una empresa joven, aprendiendo en público y construyendo con cuidado.", loopLabel: "Cómo queremos construir", reviewLabel: "Las personas mantienen el contexto y la decisión final.", statusLabel: "Útil, humano y adaptable" },
    vision: { eyebrow: "Nuestra visión", title: "Nuestra escuela es la primera de muchas.", text: "Queremos que las escuelas tengan software que respete su forma de trabajar, a las personas que las hacen funcionar y a las comunidades que las rodean. NUVRA empieza localmente, con un producto real y una escuela real, con la ambición de crecer institución por institución.", closing: "No queremos llegar con todas las respuestas. Queremos construir las correctas junto a las escuelas." },
    roadmap: { eyebrow: "Dónde estamos", title: "Una empresa en su primer capítulo real.", items: [["AHORA", "Demo funcionando dentro de nuestra escuela"], ["DESPUÉS", "Decisión sobre el uso diario"], ["LUEGO", "Mejorar lo que las personas realmente usan"], ["MÁS ADELANTE", "Construir con más instituciones"]] },
    team: { eyebrow: "El equipo", title: "Estudiantes construyendo algo útil desde Buenos Aires.", text: "Somos un equipo técnico fundado por estudiantes, combinando desarrollo de software, pensamiento de producto y experiencia directa dentro de un entorno escolar real.", members: [["Francisco Ulises González Feldman", "Fundador / Líder técnico"], ["Santino Conejo Palacios", "Co-fundador"], ["Benjamin Tomas Ison Iannello", "Primer equipo"], ["Martin Valentino Lissi", "Primer equipo"], ["Agustin Morales", "Primer equipo"]] },
    contact: { eyebrow: "Contacto", title: "Si tu escuela tiene un problema, queremos entenderlo.", text: "Para pilotos, alianzas, programas para startups o conversaciones de producto, escribile al equipo que está construyendo NUVRA desde dentro de una escuela.", button: "Hablar con el equipo", email: "founders@nuvraacademy.com.ar" },
    footer: "Nuvra Academy — Construyendo software para escuelas, una institución a la vez.",
  },
} as const;

export type Copy = (typeof copy)[Language];
