export type Language = "en" | "es";

export const copy = {
  en: {
    nav: { story: "Story", product: "Product", ai: "AI", vision: "Vision", team: "Team", contact: "Contact", cta: "Contact" },
    hero: { badge: "Built from a real school environment in Buenos Aires", headline: "A new operating layer for schools.", subtitle: "NUVRA helps educational institutions manage everyday operations from one secure, modern platform.", primary: "Discover NUVRA", secondary: "Our story", note: "Software that adapts to the way institutions actually work.", productLabel: "NUVRA / operating layer", productItems: ["Students", "Attendance", "Reports", "Permissions", "Roles", "Communication"] },
    why: { eyebrow: "01 / Why we started", title: "We did not begin NUVRA by imagining how schools might work.", lead: "We started from seeing how they actually work.", lines: ["Spreadsheets.", "Paper records.", "Disconnected systems.", "Manual reports.", "Information spread across different places."], closing: "NUVRA began as an attempt to make those everyday operations simpler, clearer and more connected." },
    school: { eyebrow: "02 / Built from a real school environment", title: "Built from a real school environment.", text: "NUVRA began inside E.E.S.T. N°1 Manuel Belgrano, a technical high school in Buenos Aires, Argentina. Working from inside a real educational environment gave us direct exposure to the workflows, limitations and operational challenges that schools face every day.", items: ["Student records", "Attendance", "Permissions", "Reports", "Roles", "Communication", "Administrative coordination"], note: "We are designing NUVRA around those realities.", location: "Santos Lugares · Buenos Aires · Argentina", stages: ["Origin", "Validation", "Product", "Scale"] },
    product: { eyebrow: "03 / What NUVRA is", title: "One system for everyday school operations.", subtitle: "NUVRA centralizes the work that keeps an institution moving — without forcing schools to become something they are not.", modules: [["Students", "Records and context"], ["Attendance", "Daily visibility"], ["Reports", "Clearer information"], ["Permissions", "Requests and review"], ["Roles", "The right access"], ["Communication", "Connected teams"], ["Workflows", "Less manual work"]] },
    ai: { eyebrow: "04 / AI for school operations", title: "AI where it actually helps.", text: "AI is not the product. It is a layer that can make school operations easier: summarize administrative information, help draft reports, surface relevant context, assist repetitive workflows and make institutional data easier to understand.", flow: [["School data", "The context already inside the institution"], ["Context", "A clearer view of what matters"], ["AI assistance", "Support for the next useful step"], ["Human review", "People keep approval and control"]], note: "A product vision grounded in practical workflows — not automation for its own sake." },
    vision: { eyebrow: "05 / Our vision", title: "Schools should not need to adapt themselves to outdated software.", text: "Software should adapt to the way institutions actually work. We want NUVRA to become a modern operational foundation for educational institutions — flexible enough for different schools, simple enough for everyday use and intelligent enough to reduce unnecessary administrative work.", closing: "We are starting locally, learning from real institutions and building with the ambition to scale much further." },
    roadmap: { eyebrow: "06 / Roadmap", title: "What we are building next.", items: [["NOW", "Core school management"], ["NEXT", "Reporting and workflow improvements"], ["THEN", "AI-assisted operations"], ["LATER", "More institutions and broader deployment"]] },
    team: { eyebrow: "07 / The team", title: "A young technical team building from Buenos Aires.", text: "We are a student-founded technical team combining software development, product thinking and direct experience inside educational environments.", members: [["Francisco Ulises González Feldman", "Founder / Technical Lead"], ["Santino Conejo Palacios", "Co-founder"], ["Benjamin Tomas Ison Iannello", "Early team"], ["Martin Valentino Lissi", "Early team"], ["Agustin Morales", "Early team"]] },
    contact: { eyebrow: "08 / Contact", title: "Building with schools, not around them.", text: "For pilots, partnerships, startup programs or product conversations, reach out to the team.", button: "Contact the team", email: "founders@nuvraacademy.com.ar" },
    footer: "Nuvra Academy — Building NUVRA for educational institutions.",
  },
  es: {
    nav: { story: "Historia", product: "Producto", ai: "IA", vision: "Visión", team: "Equipo", contact: "Contacto", cta: "Contactar" },
    hero: { badge: "Nacido desde un entorno escolar real en Buenos Aires", headline: "Una nueva capa operativa para escuelas.", subtitle: "NUVRA ayuda a instituciones educativas a gestionar sus operaciones diarias desde una plataforma segura y moderna.", primary: "Conocer NUVRA", secondary: "Nuestra historia", note: "Software que se adapta a la forma en que realmente trabajan las instituciones.", productLabel: "NUVRA / capa operativa", productItems: ["Estudiantes", "Asistencia", "Reportes", "Permisos", "Roles", "Comunicación"] },
    why: { eyebrow: "01 / Por qué empezamos", title: "No empezamos NUVRA imaginando cómo funcionan las escuelas.", lead: "Empezamos viendo cómo funcionan realmente.", lines: ["Planillas.", "Registros en papel.", "Sistemas desconectados.", "Reportes manuales.", "Información distribuida en distintos lugares."], closing: "NUVRA nació como un intento de hacer esas operaciones diarias más simples, claras y conectadas." },
    school: { eyebrow: "02 / Construido desde una escuela real", title: "Construido desde un entorno escolar real.", text: "NUVRA nació dentro de la E.E.S.T. N°1 Manuel Belgrano, una escuela técnica de Buenos Aires, Argentina. Trabajar desde un entorno educativo real nos permitió conocer directamente los flujos, limitaciones y desafíos operativos que enfrentan las escuelas todos los días.", items: ["Registros de estudiantes", "Asistencia", "Permisos", "Reportes", "Roles", "Comunicación", "Coordinación administrativa"], note: "Estamos diseñando NUVRA alrededor de esas realidades.", location: "Santos Lugares · Buenos Aires · Argentina", stages: ["Origen", "Validación", "Producto", "Escala"] },
    product: { eyebrow: "03 / Qué es NUVRA", title: "Un sistema para las operaciones escolares del día a día.", subtitle: "NUVRA centraliza el trabajo que mantiene en movimiento a una institución, sin obligar a las escuelas a convertirse en algo que no son.", modules: [["Estudiantes", "Registros y contexto"], ["Asistencia", "Visibilidad diaria"], ["Reportes", "Información más clara"], ["Permisos", "Solicitudes y revisión"], ["Roles", "El acceso correcto"], ["Comunicación", "Equipos conectados"], ["Flujos", "Menos trabajo manual"]] },
    ai: { eyebrow: "04 / IA para operaciones escolares", title: "IA donde realmente ayuda.", text: "La IA no es el producto. Es una capa que puede hacer más simples las operaciones escolares: resumir información administrativa, asistir en la redacción de reportes, mostrar contexto relevante, ayudar en flujos repetitivos y hacer que los datos institucionales sean más fáciles de entender.", flow: [["Datos escolares", "El contexto que ya existe en la institución"], ["Contexto", "Una visión más clara de lo importante"], ["Asistencia IA", "Apoyo para el siguiente paso útil"], ["Revisión humana", "Las personas mantienen la aprobación y el control"]], note: "Una visión de producto basada en flujos prácticos, no en automatizar por automatizar." },
    vision: { eyebrow: "05 / Nuestra visión", title: "Las escuelas no deberían tener que adaptarse a software anticuado.", text: "El software debería adaptarse a la forma en que realmente trabajan las instituciones. Queremos que NUVRA se convierta en una base operativa moderna para instituciones educativas: flexible para distintas escuelas, simple para el uso diario e inteligente para reducir trabajo administrativo innecesario.", closing: "Estamos empezando localmente, aprendiendo de instituciones reales y construyendo con la ambición de llegar mucho más lejos." },
    roadmap: { eyebrow: "06 / Roadmap", title: "Qué estamos construyendo ahora.", items: [["AHORA", "Núcleo de gestión escolar"], ["DESPUÉS", "Mejoras en reportes y flujos"], ["LUEGO", "Operaciones asistidas por IA"], ["MÁS ADELANTE", "Más instituciones y despliegue amplio"]] },
    team: { eyebrow: "07 / El equipo", title: "Un equipo técnico joven construyendo desde Buenos Aires.", text: "Somos un equipo técnico fundado por estudiantes, combinando desarrollo de software, pensamiento de producto y experiencia directa dentro de entornos educativos.", members: [["Francisco Ulises González Feldman", "Founder / Technical Lead"], ["Santino Conejo Palacios", "Co-founder"], ["Benjamin Tomas Ison Iannello", "Early team"], ["Martin Valentino Lissi", "Early team"], ["Agustin Morales", "Early team"]] },
    contact: { eyebrow: "08 / Contacto", title: "Construyendo con las escuelas, no alrededor de ellas.", text: "Para pilotos, alianzas, programas para startups o conversaciones de producto, escribinos.", button: "Contactar al equipo", email: "founders@nuvraacademy.com.ar" },
    footer: "Nuvra Academy — Construyendo NUVRA para instituciones educativas.",
  },
} as const;

export type Copy = (typeof copy)[Language];
